version: "3.9"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:

      - .:/app
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    command: >
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8000
      --reload

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d trading_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
